### ISSUE TITLE
Unable to run >= 0.6.1 on Edge / v8 runtimes

### ISSUE THREAD

**Issue by rawkode** [tursodatabase/libsql-client-ts#228]
```
Cannot read properties of null (reading 'split')
  TypeError: Cannot read properties of null (reading 'split')
    at globalThis.fetch (index.js:8457:59)
    at async getIsSchemaDatabase (index.js:3926:18)
    at async HttpClient2.getIsSchemaDatabase (index.js:4248:32)
TypeError
```
I've narrowed this down to a change between 0.6.0 and 0.6.1.

My code runs fine on 0.6.0, but fails on 0.6.1 and 0.6.2.

https://github.com/tursodatabase/libsql-client-ts/compare/v0.6.0...v0.6.1

**Comment by haaawk** [comment]
Please try 0.6.2 @rawkode. I believe @giovannibenussi has already fixed the problem 3 weeks ago. Could you please verify @giovannibenussi and close the issue if it's already fixed?

**Comment by rawkode** [comment]
I tried that version first, and then identified the break was introduced in 0.6.1

**Comment by haaawk** [comment]
Yes. The change was done in 6.1 -> @giovannibenussi could you please have a look on this?
