### ISSUE TITLE
LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format

### ISSUE THREAD

**Issue by yusufpazuruan** [tursodatabase/libsql-client-ts#238]
after add this   const OPTIONS: any = await db.select({id: jobs.id , name: jobs.name}).from(jobs).all() 

i see error :
why??? 

uri.js:15 Uncaught (in promise) LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format
    at parseUri (uri.js:15:15)
    at expandConfig (config.js:43:66)
    at createClient (web.js:19:91)
    at eval (index.ts:6:28)
    at (/app-pages-browser)/src/db/index.ts (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:180:1)
    at options.factory (webpack.js?v=1720738668069:715:31)
    at __webpack_require__ (webpack.js?v=1720738668069:37:33)
    at fn (webpack.js?v=1720738668069:371:21)
    at eval (VM5869 page.tsx:7:61)
    at (/app-pages-browser)/src/app/(examples)/tutorial/page.tsx (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:169:1)
parseUri @ uri.js:15
expandConfig @ config.js:43
createClient @ web.js:19
eval @ index.ts:6
(app-pages-browser)/./src/db/index.ts @ page.js:180
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
fn @ webpack.js?v=1720738668069:371
eval @ VM5869 page.tsx:7
(app-pages-browser)/./src/app/(examples)/tutorial/page.tsx @ page.js:169
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
fn @ webpack.js?v=1720738668069:371
Promise.then (async)
eval @ next-flight-client-entry-loader.js?modules=%7B%22request%22%3A%22%2Fhome%2Fuser%2Ftutorial%2Fsrc%2Fapp%2F(examples)%2Ftutorial%2Fpage.tsx%22%2C%22ids%22%3A%5B%5D%7D&server=false!:1
(app-pages-browser)/./node_modules/next/dist/build/webpack/loaders/next-flight-client-entry-loader.js?modules=%7B%22request%22%3A%22%2Fhome%2Fuser%2Ftutorial%2Fsrc%2Fapp%2F(examples)%2Ftutorial%2Fpage.tsx%22%2C%22ids%22%3A%5B%5D%7D&server=false! @ page.js:27
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
__webpack_exec__ @ page.js:1341
(anonymous) @ page.js:1342
__webpack_require__.O @ webpack.js?v=1720738668069:86
webpackJsonpCallback @ webpack.js?v=1720738668069:1397
(anonymous) @ main-app.js?v=1720738668069:9
Show 4 more frames
Show lessUnderstand this error
react-dom.development.js:9126 Uncaught LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format
    at parseUri (uri.js:15:15)
    at expandConfig (config.js:43:66)
    at createClient (web.js:19:91)
    at eval (index.ts:6:28)
    at (/app-pages-browser)/src/db/index.ts (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:180:1)
    at options.factory (webpack.js?v=1720738668069:715:31)
    at __webpack_require__ (webpack.js?v=1720738668069:37:33)
    at fn (webpack.js?v=1720738668069:371:21)
    at eval (page.tsx:7:61)
    at (/app-pages-browser)/src/app/(examples)/tutorial/page.tsx (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:169:1)
parseUri @ uri.js:15
expandConfig @ config.js:43
createClient @ web.js:19
eval @ index.ts:6
(app-pages-browser)/./src/db/index.ts @ page.js:180
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
fn @ webpack.js?v=1720738668069:371
eval @ page.tsx:7
(app-pages-browser)/./src/app/(examples)/tutorial/page.tsx @ page.js:169
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
fn @ webpack.js?v=1720738668069:371
requireModule @ react-server-dom-webpack-client.browser.development.js:198
initializeModuleChunk @ react-server-dom-webpack-client.browser.development.js:1370
parseModelString @ react-server-dom-webpack-client.browser.development.js:1699
eval @ react-server-dom-webpack-client.browser.development.js:2115
parseModel @ react-server-dom-webpack-client.browser.development.js:2107
initializeModelChunk @ react-server-dom-webpack-client.browser.development.js:1338
Chunk.then @ react-server-dom-webpack-client.browser.development.js:1130
trackUsedThenable @ react-dom.development.js:9137
useThenable @ react-dom.development.js:11483
use @ react-dom.development.js:11504
use @ react.development.js:2572
ServerRoot @ app-index.js:112
renderWithHooks @ react-dom.development.js:11121
mountIndeterminateComponent @ react-dom.development.js:16869
beginWork$1 @ react-dom.development.js:18458
beginWork @ react-dom.development.js:26927
performUnitOfWork @ react-dom.development.js:25748
workLoopConcurrent @ react-dom.development.js:25734
renderRootConcurrent @ react-dom.development.js:25690
performConcurrentWorkOnRoot @ react-dom.development.js:24504
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Show 26 more frames
Show lessUnderstand this error
app-index.js:33 Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
window.console.error @ app-index.js:33
console.error @ hydration-error-info.js:63
printWarning @ react-dom.development.js:94
error @ react-dom.development.js:68
errorHydratingContainer @ react-dom.development.js:36301
recoverFromConcurrentError @ react-dom.development.js:24593
performConcurrentWorkOnRoot @ react-dom.development.js:24542
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Show 10 more frames
Show lessUnderstand this error
react-dom.development.js:9126 Uncaught LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format
    at parseUri (uri.js:15:15)
    at expandConfig (config.js:43:66)
    at createClient (web.js:19:91)
    at eval (index.ts:6:28)
    at (/app-pages-browser)/src/db/index.ts (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:180:1)
    at options.factory (webpack.js?v=1720738668069:715:31)
    at __webpack_require__ (webpack.js?v=1720738668069:37:33)
    at fn (webpack.js?v=1720738668069:371:21)
    at eval (page.tsx:7:61)
    at (/app-pages-browser)/src/app/(examples)/tutorial/page.tsx (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:169:1)
parseUri @ uri.js:15
expandConfig @ config.js:43
createClient @ web.js:19
eval @ index.ts:6
(app-pages-browser)/./src/db/index.ts @ page.js:180
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
fn @ webpack.js?v=1720738668069:371
eval @ page.tsx:7
(app-pages-browser)/./src/app/(examples)/tutorial/page.tsx @ page.js:169
options.factory @ webpack.js?v=1720738668069:715
__webpack_require__ @ webpack.js?v=1720738668069:37
fn @ webpack.js?v=1720738668069:371
requireModule @ react-server-dom-webpack-client.browser.development.js:198
initializeModuleChunk @ react-server-dom-webpack-client.browser.development.js:1370
parseModelString @ react-server-dom-webpack-client.browser.development.js:1699
eval @ react-server-dom-webpack-client.browser.development.js:2115
parseModel @ react-server-dom-webpack-client.browser.development.js:2107
initializeModelChunk @ react-server-dom-webpack-client.browser.development.js:1338
Chunk.then @ react-server-dom-webpack-client.browser.development.js:1130
trackUsedThenable @ react-dom.development.js:9137
useThenable @ react-dom.development.js:11483
use @ react-dom.development.js:11504
use @ react.development.js:2572
ServerRoot @ app-index.js:112
renderWithHooks @ react-dom.development.js:11121
mountIndeterminateComponent @ react-dom.development.js:16869
beginWork$1 @ react-dom.development.js:18458
beginWork @ react-dom.development.js:26927
performUnitOfWork @ react-dom.development.js:25748
workLoopConcurrent @ react-dom.development.js:25734
renderRootConcurrent @ react-dom.development.js:25690
performConcurrentWorkOnRoot @ react-dom.development.js:24504
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Show 26 more frames
Show lessUnderstand this error
app-index.js:33 The above error occurred in the <ServerRoot> component:

    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:112:27)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:117:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
window.console.error @ app-index.js:33
console.error @ hydration-error-info.js:63
logCapturedError @ react-dom.development.js:15295
update.callback @ react-dom.development.js:15321
callCallback @ react-dom.development.js:8696
commitCallbacks @ react-dom.development.js:8743
commitLayoutEffectOnFiber @ react-dom.development.js:21461
commitLayoutEffects @ react-dom.development.js:22912
commitRootImpl @ react-dom.development.js:26226
commitRoot @ react-dom.development.js:26077
commitRootWhenReady @ react-dom.development.js:24749
finishConcurrentRender @ react-dom.development.js:24714
performConcurrentWorkOnRoot @ react-dom.development.js:24559
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Show 16 more frames
Show lessUnderstand this error
react-dom.development.js:16571 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:16571:57)
    at beginWork$1 (react-dom.development.js:18486:14)
    at beginWork (react-dom.development.js:26927:14)
    at performUnitOfWork (react-dom.development.js:25748:12)
    at workLoopSync (react-dom.development.js:25464:5)
    at renderRootSync (react-dom.development.js:25419:7)
    at recoverFromConcurrentError (react-dom.development.js:24597:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:24542:26)
    at workLoop (scheduler.development.js:256:34)
    at flushWork (scheduler.development.js:225:14)
updateHostRoot @ react-dom.development.js:16571
beginWork$1 @ react-dom.development.js:18486
beginWork @ react-dom.development.js:26927
performUnitOfWork @ react-dom.development.js:25748
workLoopSync @ react-dom.development.js:25464
renderRootSync @ react-dom.development.js:25419
recoverFromConcurrentError @ react-dom.development.js:24597
performConcurrentWorkOnRoot @ react-dom.development.js:24542
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
Show 11 more frames
Show lessUnderstand this error
react-dom.development.js:26325 Uncaught LibsqlError: URL_INVALID: The URL 'undefined' is not in a valid format
    at parseUri (uri.js:15:15)
    at expandConfig (config.js:43:66)
    at createClient (web.js:19:91)
    at eval (index.ts:6:28)
    at (/app-pages-browser)/src/db/index.ts (https://3000-idx-tutorial-1720417706157.cluster-a3grjzek65cxex762e4mwrzl46.cloudworkstations.dev/_next/static/chunks/app/(examples)/tutorial/page.js:180:1)
    at options.factory (webpack.js?v=1720738668069:715:31)
    at __webpack_require__ (webpack.js?v=1720738668069:37:33)
    at fn (webpack.js?v=1720738668069:371:21)
    at eval (page.tsx:7:61)

**Comment by notrab** [comment]
This is most often always caused by environment variables not being sourced correctly. The error above `The URL 'undefined' is not in a valid format` tends to point to no URL being provided.

Please check it works with hard coded values, and then again with environment variables.

If this continues to be an issue, we can reopen.
